# This file was inspired from https://github.com/LibrePCB/LibrePCB/blob/master/.travis.yml

#
# General config
#
branches:
  only:
  - master
sudo: required
language: cpp

# Enable caching
#cache: ccache

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
		- packaging@openmittsu.de

#
# Configurations
#
matrix:
  fast_finish: true

    ###
    # Stage: Build
    ###

    # OS X + GCC
    - os: osx
      compiler: gcc
      env: 
	  after_failure:
        - find build -iname '*err*.log' -type f -print -exec cat {} \;
    # OS X + Clang
    - os: osx
      compiler: clang
      env: 
	  after_failure:
        - find build -iname '*err*.log' -type f -print -exec cat {} \;
	# Ubuntu 14.04 + GCC 4.8 + Qt 5.2
    - os: linux
      dist: trusty
      compiler: gcc
      env: DEPLOY_APPIMAGE=false QT_BASE="trusty"
	  after_failure:
        - find build -iname '*err*.log' -type f -print -exec cat {} \;
    # Ubuntu 14.04 + Clang + Qt from PPA (https://launchpad.net/~beineri) + AppImage deployment
    - os: linux
      dist: trusty
      compiler: clang
      env: DEPLOY_APPIMAGE=true QT_BASE="qt59" QT_PPA="ppa:beineri/opt-qt593-trusty"
      after_failure:
        - find build -iname '*err*.log' -type f -print -exec cat {} \;

install:
  - source ./travis/installDependencies.sh # source required because it modifies the environment

script:
  - ./travis/build.sh
  - ./travis/runTests.sh
  - ./travis/buildAppimage.sh
