# This file was inspired from https://github.com/LibrePCB/LibrePCB/blob/master/.travis.yml

#
# General config
#
branches:
  only:
  - master
sudo: required
dist: trusty
language: cpp

# Enable caching
#cache: ccache

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
        - packaging@openmittsu.de

#
# Configurations
#
matrix:
  fast_finish: true
  include:
    # OS X + GCC
    - os: osx
      compiler: gcc
    # OS X + Clang
    - os: osx
      compiler: clang
      env: DEPLOY_APPIMAGE=true
    # Ubuntu 14.04 + GCC 4.8 + Qt 5.2
    - os: linux
      compiler: gcc
      env: DEPLOY_APPIMAGE=false QT_BASE="trusty"
    # Ubuntu 14.04 + Clang + Qt from PPA (https://launchpad.net/~beineri) + AppImage deployment
    - os: linux
      compiler: clang
      env: DEPLOY_APPIMAGE=true QT_BASE="qt59" QT_PPA="ppa:beineri/opt-qt593-trusty"

after_failure:
  - find build -iname '*err*.log' -type f -print -exec cat {} \;

before_install:
  - chmod +x ./travis/installDependencies.sh
  - chmod +x ./travis/build.sh
  - chmod +x ./travis/runTests.sh
  - chmod +x ./travis/buildAppImage.sh

install:
  - source ./travis/installDependencies.sh

script:
  - ./travis/build.sh
  - ./travis/runTests.sh
  - ./travis/buildAppImage.sh

deploy:
  provider: bintray
  file: ./travis/bintray.json
  user: "${BINTRAY_USER}"
  key: "${BINTRAY_API_KEY}"
  skip_cleanup: true
  on:
    branch: master
    condition: ${DEPLOY_APPIMAGE} = true
  